par(mfrow = c(2,2), mar = c(4,4,2,1), oma = c(0,0,2,0))
plot(hpc_complete$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
plot(hpc_complete$Voltage, type = "l", ylab = "Voltage",xlab = "datetime")
plot(hpc_complete$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(hpc_complete$Sub_metering_2, col = "red")
lines(hpc_complete$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"), lwd = c(1,1,1), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(hpc_complete$Global_reactive_power, type = "l", ylab = "Glboal_reactive_power", xlab = "datetime")
dev.copy(png, file = "plot4.png")